### ISSUE TITLE
Possible use of rsync snapshot?

### ISSUE THREAD

**Issue by BenjaminHCCarr** [laurent22/rsync-time-backup#103]
More a question than an issue.
Have you looked at `rsnapshot` (https://github.com/rsnapshot/rsnapshot)?

This has been implemented on linux:
https://www.lynda.com/Linux-tutorials/Backup-snapshots-rsync/604236/642414-4.html

I found your code from the `PR` to homebrew: Homebrew/homebrew-core#21065

But have been using plain rsync over ssh for remote backups and would prefer to move to versioning but haven't had time.

If this is something you explored and disregarded I would love to hear it. My remote targets are EXT4 and ZFS (BSD/OpenZFS).

**Comment by braian87b** [comment]
I think that this code is intended to behave as more as possible equal to the original Mac TimeMachine's backups... but using rsync... rsnapshot have similar feature, but have some differences on directory creation and how it needs to be configured, it takes 5 to 15 more minutes more to configure and test in comparision to this script that is more limited but also simple.

Since I even had the need to have unique snapshots (having each snapshot only the modified files between previous backup, I created a script that compares each file and if it has the same inode then removes it from the previous backup. In my work it is more esier to users to understand that they can find the previous versions of files in different snapshot, if the file is not there then is because the file have not been modified at that time... that also allow to remove empty directory trees of snapshots at some times where none of the files were modified in any way.

**Comment by thomas-mc-work** [comment]
I've used that one before. But rsync-time-backup is much more lightweight and easier to install (no perl dependency) which i like very much.

**Comment by laurent22** [comment]
I think rsnapshot also uses rsync. Rsync-time-backup is just a different approach
