### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by scorpio2k2** [laurent22/rsync-time-backup#40]
how do I use this? 
Is a classical cron  script?

**Comment by laurent22** [comment]
It's a regular Bash script, the command is:

    rsync_tmbackup.sh <source> <destination> [excluded-pattern-path]

And it can also be setup as a cron job like any other command.

**Comment by scorpio2k2** [comment]
Thanks. I thought that I need to put it at startup and the script will work like time machine. hourly, daily and weekly backups.

**Comment by lorentrogers** [comment]
May be worthwhile to add a bit about usage in the readme? Perhaps examples of common setups?

**Comment by laurent22** [comment]
@lorentrogers, we could indeed add a section about it, as long as it's reasonably short (since describing how cron or, say, scheduled tasks on Windows work is a bit out of scope). Maybe an example of cron command like `0 22 * * * /path/to/rsync_tmbackup.sh /source/ /dest/ /path/to/excluded_patterns.txt`?

**Comment by lorentrogers** [comment]
Examples are included in this more recent version: https://github.com/eaut/rsync-time-backup

**Comment by laurent22** [comment]
Fixed in 5a0fd5f3b107ab9a01e6ab9c57a8ae2167a2492c. There's now an example to make it work more or less like Time Machine using a cron script.
