### ISSUE TITLE
Implement backup size limit

### ISSUE THREAD

**Issue by RickyB98** [laurent22/rsync-time-backup#53]
One feature that's missing in macOS (yeah, let's get used to call it like that ;)) Time Machine backups is the ability to set a size limit to the backup, so that once that limit is exceeded older backups get automatically purged. It would be a nice feature if you want to use your drive not only for backups, but also as an ordinary drive to store files onto.

**Comment by mro** [comment]
hm, a `du -ksc` can take quite long, while ensuring a certain amount of remaining free space (prior and after?) via `df -k` is lightning fast.

What do you think?

**Comment by RickyB98** [comment]
I probably didn't make myself clear enough. What I meant was that a feature to impose a total backup size limit could be implemented to make sure that the script won't eventually use up all of the space on the drive. I'm not sure what you mean to be honest.

**Comment by mro** [comment]
as far as I understand TimeMachine does 

- a pre-flight calculation of the space required by the upcoming backup
- purge old backups until that amount is free
- actually do the backup
- additionally backup everything that's changed while doing the backup

while I think doing a pre-flight size calculation isn't feasible with rsync (correct me if I'm wrong), I think it may be better than nothing to ensure the backup doesn't flood the disk entirely by ensuring a certain amount of free space (and hope that's enough buffer to do a single backup).

**Comment by RickyB98** [comment]
Yes, I do have an idea about what du and df are, even though I don't use them so much often. However that was not the point I got lost on. Beside the fact that the script should check whether it has enough space before actually backing up (which I think it does already, I took a look at the script), what I was asking was to have an option that the script would accept to somehow fake the free space left before making the backup, so that you can make sure that overall, for a X GB drive, your backup won't exceed Y GB (Y chosen arbitrarily) where Y<X. And so you can use the remaining (X-Y) gigabytes for other purposes.

**Comment by laurent22** [comment]
Currently we don't calculate the remaining space, we simply keep copying till the drive is full. At that point, the previous backups are deleted, and the current backup resumes.

We don't calculate in advance because it's difficult to know how much space an incremental backup is going to take, the only way is to run rsync with the `--dry-run` flag (which is time consuming). There's a previous related discussion about this here - https://github.com/laurent22/rsync-time-backup/issues/1

If someone is willing to implement the feature as an option though, I'd be willing to integrate it.

**Comment by lfulcomer** [comment]
Would it be possible to check for free space available on local transfers, since they don't use deltas anyway? 
Ricky, this is how I handle what you're asking about: [Disk Quotas](https://wiki.archlinux.org/index.php/Disk_quota) rather than try and re-invent the wheel via rsync. 

My problem is for some reason, in some scripts on CentOS, rsync ignores the 'disk full' notification and continues the job, even though it is not writing any files. This is especially perplexing when it happens to a job running to tape. The drive is definitely notifying systemd that it is full, but... even stranger, this only happens when I don't turn debugging on in either systemd or rsync... :)

**Comment by laurent22** [comment]
Only solution to this problem is quite complex and would make backups take a longer time, so it's indeed better to leave that to other tools such as disk quotas.
