### ISSUE TITLE
Support command line arguments

### ISSUE THREAD

**Issue by laurent22** [laurent22/rsync-time-backup#54]
Add support for command line arguments, so that new features can be more easily integrated.

Whatever system is used to parse arguments, it must not break existing scripts that rely on rsync-time-backup. One option would be to support a usage such as:

    ./rsync_tm_backup.sh [args] <source> <destination> [<exclusion_file>]

[args] being entirely optional means the new usage will be compatible with existing scripts.

**Comment by laurent22** [comment]
Also neither `getopts`, which doesn't support long arguments, not `getopt`, which is unreliable should be used. A good example of manually parsing there: http://mywiki.wooledge.org/BashFAQ/035

**Comment by laurent22** [comment]
Done in 9c5046e5182b5565c90f5309af00f97efb8d68d2

**Comment by JohnKaul** [comment]
Arguments without flags ("positional arguments" I guess you'd call them) is a dangerous way to handle arguments, when dealing with peoples backups. -i.e. b->a instead of a->b because the arguments happened to have been given in that order. What I mean to say is that breaking (not keeping) backwards compatibility may, in this case, be a good idea.

Also, although long options are not the "unix way"* I do think the end-user having the option to be specific with the options in this case is a good idea.

[*] "--" means that the remaining arguments should not be treated as options.

**Comment by laurent22** [comment]
The script more or less follow the rsync way of handling arguments, which usage is `rsync [OPTION...] SRC... [DEST]` and rsync also uses long options (which I think make scripts more readable as it means there's no need to look up the meaning of options).

I've been quite careful to make the script as safe as possible with very little risk of losing data, since I know the mess that a bad sync can create. There's the drive marker, which forces the user to explicitly mark a drive as a destination, so it won't work if the arguments are mixed up. Also each backup set is created in its own timestamped directory so there's no risk of getting file overwritten or deleted.

**Comment by JohnKaul** [comment]
I agree about supporting long options.
