### ISSUE TITLE
Expire before/after backup

### ISSUE THREAD

**Issue by jurgihub** [laurent22/rsync-time-backup#83]
Maybe this has already been discussed before, and if not, I guess there are some good reasons why expiring should occur before backing up (I can come up with some good reasons myself). However, consider this:

During some testing yesterday (playing around with launchd on OSX), in about half an hour I created a couple of dozen backups on my remote server. Today, at the start of a backup more than 24 hours after that test, the script obviously wants to expire yesterday's backups (save the last one). Needless to say that this takes a lot of time, and no backup starts as long as there is expiring going on. In fact, it takes so long that when I'm done doing my bit of work on my laptop, I just close the lid, which stops the script. And since the script was still expiring old backups, no new backup has been made. In fact, it's now rather late at night, and my hourly script still needs to perform a full backup today (because it keeps on expiring those old backups, and I'm always done working before it can actually start backing up).

Point being: could backups be expired *after* doing the actual backup? That way, at least those backups won't be held back by expiring a couple of dozen old ones. I know this particular situation of mine might be rather extreme, but I think there is something to be said of backup up first, and deleting old stuff later (that's what TimeMachine does as well, actually).

**Comment by laurent22** [comment]
I'd be fine with a pull request on this. The reason it's like this at the moment is simply to make space on the device before starting the backup (so that it doesn't get interrupted), but I can see there would also be advantages doing it after the backup has been done.

If we change this, the expiration logic when the device is full will need to be changed: instead of simply deleting the old backups (like now), it should call the code under "Purge certain old backups before beginning new backup." (which should probably be moved to its own function). And then this code should be called again once the backup is successful.

It should also handle the case where the expiration logic has been executed and there's still not enough space in which case, like now, the oldest backup should be expired.
