### ISSUE TITLE
Only redo link to latest after backup complete if backup is not empty

### ISSUE THREAD

**Issue by geek1011** [laurent22/rsync-time-backup#84]
I use this script to pull backups from remote computers. If they are not accessible, and rsync does not transfer any files, this script should revert the symlink to the previous backup.

**Comment by laurent22** [comment]
The symlink to the last backup is always added because it's not possible to interpret the rsync errors - for example, for some users an error due to an inaccessible file is acceptable and so they still want the symlink to be created in this case. Also if a backup set is empty it could be an error or maybe it's normal if the source is temporarily empty too. Basically it's not possible to know so the symlink is always added.

I think instead the caller should check the exit code of the script (which is != 0 on error) and decide what to do in this case - search for errors in the log, or check the backup size, etc. and then restore the symlink as needed.

**Comment by laurent22** [comment]
That being said, if it's over ssh, and ssh reports an error which is not handled by the script then it's indeed a bug. In that please provide a way to replicate the bug, or a log or output from the console.

**Comment by geek1011** [comment]
I think it should not create the symlink if the backup set is empty, or if the host is unreachable.

A way to replicate the bug is to set the backup source to a server which is not accessible over SSH.
